### ISSUE TITLE
Using a custom mat-autocomplete for editing and binding to datatable events

### ISSUE THREAD

**Issue by st-clair-clarke** [krishna-agarwal/momentum-table#28]
Hi
I have the following component that wraps a mat-autocomplete component and is contained in column of the datatable:

```
<m-column field = 'duration'
            header = 'Duration'
            [editable] = 'false'
            [sortable] = 'false'>

    <ng-template let-col
                 mTemplate = 'body'>
    <pim-mat-autocomplete
        #durationAuto
        [required] = 'true'
        [maxLength] = '50'
        [minLength] = '5'
        svgPrefixIcon = 'calendar-clock1l'
        [options] = 'durationOptions'
        [validate] = '"alphaNumericSentence"'
        [width] = 'width'
        (selectionData) = 'getDuration($event)'></pim-mat-autocomplete>
    </ng-template>
  </m-column>
```

To use this custom component I have to set [editable] = 'false' for it not to be substituted by the default editor. But now I have lost the events that tie the default editor with such as row selection with the returned row data.

Is there a way I can substitute a custom editor for the default and still have the default events behave as normal?

Thanks

**Comment by krishna-agarwal** [comment]
Hi
To use custom edit component, you need to set editable true and add it in editor template.
```
<m-column field = 'duration'
            header = 'Duration'
            [editable] = 'true'
            [sortable] = 'false'>
    <ng-template let-col let-row="row" mTemplate="editor">
        <pim-mat-autocomplete></pim-mat-autocomplete>
    </ng-template>
</m-column>
```

**Comment by st-clair-clarke** [comment]
The `<pim-mat-autocomplete></pim-mat-autocomplete>` is rendered in the UI at initillization but on clicking it is immediately substituted with the default text editor. Maybe something is missing.

Thanks

**Comment by krishna-agarwal** [comment]
Could you please provide an example in stackblitz?
