### ISSUE TITLE
Changing the default height of m-table

### ISSUE THREAD

**Issue by st-clair-clarke** [krishna-agarwal/momentum-table#31]
Hi Krishna,
Is there a way for me tho change the default height of momentum-table?

Cheers

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke 
Sorry for the late reply, I was out of town for a while.
I am exposing css variable to customise the css, will update you once it's done.
Meanwhile you can edit css using ``::ng:deep`` 
eg. 
```
:host ::ng-deep .table-container{
  height: 700px;
}
```

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke 
I have exposed some css variables to customise css.
Update the package and then You can use them as follows
```
:host{
  --table-height: inherit;
  --column-padding: 0 28px;
  --first-column-padding: 0 0 0 24px;
  --last-column-padding: 0 24px 0 0;

  --row-height: 47px;
  --table-header-height: 55px;
  --table-footer-height: 51px;

  --card-footer-height: 64px;
  --card-footer-height: 56px;
}
```
Also I have updated the demo.
