### ISSUE TITLE
demo console not printing correctly

### ISSUE THREAD

**Issue by st-clair-clarke** [krishna-agarwal/momentum-table#42]
Hi,
The demo at [https://stackblitz.com/edit/momentum-table-demo](https://stackblitz.com/edit/momentum-table-demo is printing undefined for selections etc.

Cheers

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke 
Thanks for pointing out, there was a typo while binding selection property. Have fixed that.
Let me know if you face any other issue, will try to resolve.
Thank You.
