### ISSUE TITLE
errors when momentum table module is added to angular6 application appModule

### ISSUE THREAD

**Issue by st-clair-clarke** [krishna-agarwal/momentum-table#44]
Hi Krishna,
I have updated to angular6. However I am now experiencing problems with momentum-table. Below is the the error just trying to load the module:

```
compiler.js:215 Uncaught Error: Template parse errors:
Can't bind to 'floatPlaceholder' since it isn't a known property of 'mat-form-field'.
1. If 'mat-form-field' is an Angular component and it has 'floatPlaceholder' input, then verify that it is part of this module.
2. If 'mat-form-field' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("eader.searchField == 'line'" class="line-search">
            <mat-form-field class="m-search-form" [ERROR ->][floatPlaceholder]="'never'" [ngClass]="[searchOpen ? 'search-open' : 'search-close']">
```
Maybe some minor changes in the angular6 release.  Let me know what you think.

Cheers

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke 
There are some breaking changes in Angular 6, will fix them soon.

Thank you.

**Comment by st-clair-clarke** [comment]
Great. And thanks.

**Comment by st-clair-clarke** [comment]
Hi, Krishna,
Any progress on angular6 upgrade on momentum table? I am currently porting ng5 to ng6 and momentum-table is a work-horse for my app. Looking forward to the upgrade.

Thanks

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke 
Sorry I was too busy last week,
Will surly upgrade to ng6 by this weekend.

Thanks

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke 
momentum-table is upgraded to support Angular-6.
Please upgrade momentum-table package and let me know if it's woking as expected.

Cheers :)
